#############################################################################
# Makefile for building: PresentRadio.app/Contents/MacOS/PresentRadio
# Generated by qmake (2.01a) (Qt 4.6.0) on: Sat Jan 30 22:23:45 2010
# Project:  PresentRadio.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o Makefile PresentRadio.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_PHONON_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -arch i386 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch i386 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.6/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtNetwork.framework/Versions/4/Headers -I/usr/include/QtNetwork -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/Library/Frameworks/QtXml.framework/Versions/4/Headers -I/usr/include/QtXml -I/Library/Frameworks/phonon.framework/Versions/4/Headers -I/usr/include/phonon -I/usr/include -I/usr/include/phonon_compat/phonon -I/usr/include/phonon_compat -I/usr/include/phonon/Phonon -I. -I. -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch i386
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -llastfm -lqjson -framework IOBluetooth -framework Foundation -framework AppKit -framework phonon -framework QtXml -framework QtGui -framework QtNetwork -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		bluetoothdevicemodel.cpp \
		radio.cpp moc_mainwindow.cpp \
		moc_bluetoothdevicemodel.cpp \
		moc_radio.cpp
OBJECTS       = BluetoothDeviceInquiryMac.o \
		CocoaInitializer.o \
		main.o \
		mainwindow.o \
		bluetoothdevicemodel.o \
		radio.o \
		moc_mainwindow.o \
		moc_bluetoothdevicemodel.o \
		moc_radio.o
DIST          = /usr/local/Qt4.6/mkspecs/common/unix.conf \
		/usr/local/Qt4.6/mkspecs/common/mac.conf \
		/usr/local/Qt4.6/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.6/mkspecs/qconfig.pri \
		/usr/local/Qt4.6/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.6/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.6/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.6/mkspecs/features/debug.prf \
		/usr/local/Qt4.6/mkspecs/features/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/x86.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.6/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.6/mkspecs/features/qt.prf \
		/usr/local/Qt4.6/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.6/mkspecs/features/moc.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.6/mkspecs/features/resources.prf \
		/usr/local/Qt4.6/mkspecs/features/uic.prf \
		/usr/local/Qt4.6/mkspecs/features/yacc.prf \
		/usr/local/Qt4.6/mkspecs/features/lex.prf \
		/usr/local/Qt4.6/mkspecs/features/include_source_dir.prf \
		PresentRadio.pro
QMAKE_TARGET  = PresentRadio
DESTDIR       = 
TARGET        = PresentRadio.app/Contents/MacOS/PresentRadio

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-arch \
		i386 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile PresentRadio.app/Contents/PkgInfo PresentRadio.app/Contents/Resources/empty.lproj PresentRadio.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) PresentRadio.app/Contents/MacOS/ || $(MKDIR) PresentRadio.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PresentRadio.pro  /usr/local/Qt4.6/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.6/mkspecs/common/unix.conf \
		/usr/local/Qt4.6/mkspecs/common/mac.conf \
		/usr/local/Qt4.6/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.6/mkspecs/qconfig.pri \
		/usr/local/Qt4.6/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.6/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.6/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.6/mkspecs/features/debug.prf \
		/usr/local/Qt4.6/mkspecs/features/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/x86.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.6/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.6/mkspecs/features/qt.prf \
		/usr/local/Qt4.6/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.6/mkspecs/features/moc.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.6/mkspecs/features/resources.prf \
		/usr/local/Qt4.6/mkspecs/features/uic.prf \
		/usr/local/Qt4.6/mkspecs/features/yacc.prf \
		/usr/local/Qt4.6/mkspecs/features/lex.prf \
		/usr/local/Qt4.6/mkspecs/features/include_source_dir.prf \
		/Library/Frameworks/phonon.framework/phonon.prl \
		/Library/Frameworks/QtGui.framework/QtGui.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl \
		/Library/Frameworks/QtXml.framework/QtXml.prl \
		/Library/Frameworks/QtNetwork.framework/QtNetwork.prl
	$(QMAKE) -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o Makefile PresentRadio.pro
/usr/local/Qt4.6/mkspecs/common/unix.conf:
/usr/local/Qt4.6/mkspecs/common/mac.conf:
/usr/local/Qt4.6/mkspecs/common/mac-g++.conf:
/usr/local/Qt4.6/mkspecs/qconfig.pri:
/usr/local/Qt4.6/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.6/mkspecs/features/qt_config.prf:
/usr/local/Qt4.6/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.6/mkspecs/features/default_pre.prf:
/usr/local/Qt4.6/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.6/mkspecs/features/mac/dwarf2.prf:
/usr/local/Qt4.6/mkspecs/features/debug.prf:
/usr/local/Qt4.6/mkspecs/features/default_post.prf:
/usr/local/Qt4.6/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.6/mkspecs/features/mac/x86.prf:
/usr/local/Qt4.6/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.6/mkspecs/features/warn_on.prf:
/usr/local/Qt4.6/mkspecs/features/qt.prf:
/usr/local/Qt4.6/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.6/mkspecs/features/moc.prf:
/usr/local/Qt4.6/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.6/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.6/mkspecs/features/resources.prf:
/usr/local/Qt4.6/mkspecs/features/uic.prf:
/usr/local/Qt4.6/mkspecs/features/yacc.prf:
/usr/local/Qt4.6/mkspecs/features/lex.prf:
/usr/local/Qt4.6/mkspecs/features/include_source_dir.prf:
/Library/Frameworks/phonon.framework/phonon.prl:
/Library/Frameworks/QtGui.framework/QtGui.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
/Library/Frameworks/QtXml.framework/QtXml.prl:
/Library/Frameworks/QtNetwork.framework/QtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o Makefile PresentRadio.pro

PresentRadio.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) PresentRadio.app/Contents || $(MKDIR) PresentRadio.app/Contents 
	@$(DEL_FILE) PresentRadio.app/Contents/PkgInfo
	@echo "APPL????" >PresentRadio.app/Contents/PkgInfo
PresentRadio.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) PresentRadio.app/Contents/Resources || $(MKDIR) PresentRadio.app/Contents/Resources 
	@touch PresentRadio.app/Contents/Resources/empty.lproj
	
PresentRadio.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) PresentRadio.app/Contents || $(MKDIR) PresentRadio.app/Contents 
	@$(DEL_FILE) PresentRadio.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,PresentRadio,g" -e "s,@TYPEINFO@,????,g" /usr/local/Qt4.6/mkspecs/macx-g++/Info.plist.app >PresentRadio.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/PresentRadio1.0.0 || $(MKDIR) .tmp/PresentRadio1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/PresentRadio1.0.0/ && $(COPY_FILE) --parents BluetoothDeviceInquiryMac.mm CocoaInitializer.mm .tmp/PresentRadio1.0.0/ && $(COPY_FILE) --parents BluetoothDeviceInquiryMac.h CocoaInitializer.h mainwindow.h bluetoothdeviceinquiryinterface.h bluetoothdevicemodel.h radio.h .tmp/PresentRadio1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp bluetoothdevicemodel.cpp radio.cpp .tmp/PresentRadio1.0.0/ && $(COPY_FILE) --parents BluetoothDeviceInquiryMac.mm CocoaInitializer.mm .tmp/PresentRadio1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/PresentRadio1.0.0/ && (cd `dirname .tmp/PresentRadio1.0.0` && $(TAR) PresentRadio1.0.0.tar PresentRadio1.0.0 && $(COMPRESS) PresentRadio1.0.0.tar) && $(MOVE) `dirname .tmp/PresentRadio1.0.0`/PresentRadio1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/PresentRadio1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r PresentRadio.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all: BluetoothDeviceInquiryMac.o CocoaInitializer.o
compiler_objective_c_clean:
	-$(DEL_FILE) BluetoothDeviceInquiryMac.o CocoaInitializer.o
BluetoothDeviceInquiryMac.o: BluetoothDeviceInquiryMac.h \
		bluetoothdeviceinquiryinterface.h \
		BluetoothDeviceInquiryMac.mm
	gcc -c $(QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS) $(DEFINES) $(INCPATH) BluetoothDeviceInquiryMac.mm -o BluetoothDeviceInquiryMac.o

CocoaInitializer.o: CocoaInitializer.h \
		CocoaInitializer.mm
	gcc -c $(QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS) $(DEFINES) $(INCPATH) CocoaInitializer.mm -o CocoaInitializer.o

compiler_moc_header_make_all: moc_mainwindow.cpp moc_bluetoothdevicemodel.cpp moc_radio.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_bluetoothdevicemodel.cpp moc_radio.cpp
moc_mainwindow.cpp: radio.h \
		bluetoothdeviceinquiryinterface.h \
		mainwindow.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ mainwindow.h -o moc_mainwindow.cpp

moc_bluetoothdevicemodel.cpp: bluetoothdeviceinquiryinterface.h \
		bluetoothdevicemodel.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ bluetoothdevicemodel.h -o moc_bluetoothdevicemodel.cpp

moc_radio.cpp: radio.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ radio.h -o moc_radio.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/Developer/Tools/Qt/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_objective_c_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		radio.h \
		bluetoothdeviceinquiryinterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		radio.h \
		bluetoothdeviceinquiryinterface.h \
		ui_mainwindow.h \
		BluetoothDeviceInquiryMac.h \
		CocoaInitializer.h \
		bluetoothdevicemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

bluetoothdevicemodel.o: bluetoothdevicemodel.cpp bluetoothdevicemodel.h \
		bluetoothdeviceinquiryinterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bluetoothdevicemodel.o bluetoothdevicemodel.cpp

radio.o: radio.cpp Radio.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o radio.o radio.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_bluetoothdevicemodel.o: moc_bluetoothdevicemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bluetoothdevicemodel.o moc_bluetoothdevicemodel.cpp

moc_radio.o: moc_radio.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_radio.o moc_radio.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

